# Generated by Django 5.0.4 on 2024-08-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='static/portada', verbose_name='Imagen del libro')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('sinopsis', models.TextField(default='Sinopsis No Disponible')),
                ('editorial', models.CharField(blank=True, max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('cant_paginas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, max_length=50, null=True)),
                ('encuadernacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('I', 'Indefinido'), ('F', 'Libro Fisico'), ('A', 'Audio Libro'), ('E', 'Ebook')], default='I', max_length=15)),
                ('narrador', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion', models.SmallIntegerField(blank=True, null=True)),
                ('extension_archivo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
