# Generated by Django 5.0.4 on 2024-08-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('total', models.BigIntegerField(blank=True, default=0, null=True)),
                ('titulo', models.TextField(max_length=250)),
            ],
        ),
    ]
