# Generated by Django 5.0.4 on 2024-08-08 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estrellas', models.CharField(max_length=5)),
                ('comentario', models.TextField(max_length=500)),
                ('libro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Libro.libro')),
            ],
        ),
    ]
