# Generated by Django 5.0.4 on 2024-08-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('origen', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('N', 'Enviado'), ('C', 'Cancelado')], max_length=1)),
            ],
        ),
    ]
